#! /bin/bash

#  run script for
#  validating the SPM implementation on ice particles
#
#  tcase_id  103
#    runs 1d model with a BND zone container on top of the domain.
#    Initially, particles are located in three 10m-cells above 
#    the top domain boundary and generated every few seconds 
#    to maintain the constant -nrp0- number in the three levels
#    during the run.
#
#    This test case is meant to:
#    
#    a) exploid more realistic setting with constant influx of ice particles
#       falling through the top boundary;
#
#    b) examine the convergence of the SDM method under sedimentation, 
#       deposition/sublimation, riming, and aggregation;
#
#    c) investigatate the influence vertical resolution by varying 'nz'
#       for a given height.
#
#    d) test storing of the agrregation history (agg_hist >= 0)


set -e
export OMP_NUM_THREADS=4

# pre-scaled variables
dom_top="3850."  # [m]
dom_bottom="0."
nz=200           # number of vertical cells
xi0=100          # [RP/SP]
dtc=5            # [s]
nrp=2            # [1000 RP/m3]
lwc="0"          # [1/10000 kg/m3]
iwc="5"          # [1/100000 kg/m3]
box_area="500"   # [1/100 m2]
wdm=10           # [10**-6 kg/m3]
h1=$6 #10            # [100 m]
h2=$7 #20            # [100 m]
if [[ $7 -gt $6 ]]; then #if riming in setup
	rt=1             # rime type: 0-no-riming, 1-cont, 2-stoch
else
	rt=0
fi
ncl=$8            # [1/1000 SP/sm3 *30 because xi0*30 in mo_nucleation.f90] #this is per SP so define the RP by the scaling of ncl below #change it when you change xi0!! 
nclmass=$9
#ncl lower than 6 will fail because of FLOOR(nclrate * grid%dbox * dtc) in mo_sp_nml.f90
vt=1             # terminal velocity: 1) Heymsfield, 2) Khvorostyanov
geo=3            # snow geometry: 1: bulk, 2: fillin, 3: similarity
agggeo=$5         # ! 1: M96 mixed agg, 2: MK96 plates + M96 mixed agg, 3: monomer dependent plates
if [[ "$agggeo" -eq 9999 ]] ; then agggeo=1 ; fi
agg=2            # 0: no aggregation. 1: Golovin kernel 2: hydrodynamic kernel
dep=1            # 0: no diffusion, 1: vapour diffusion
meltt=0           # 0: no melting, 1: melting activated
multt=0          # 0: no ice multiplication, 1: rime splintering
stick=$3		 # 0: E_s=1, 1: PK97, 2: Connolly12, 3: 0.5*Connolly12
if [[ "$stick" -eq 9999 ]] ; then stick=1 ; fi #ssat [1/1000]
ssat=$2 #read ssat from governing script or set default in next line to 0.01 if ssat is set to 9999 #ssat [1/1000]
if [[ "$ssat" -eq 9999 ]] ; then ssat=100 ; fi #ssat [1/1000]

model_setup=$4
#give the MCSnowgeom a more telling name
if [[ "$5" -eq 1 ]]; then agggeo_string="constant"
elif [[ "$5" -eq 2 ]]; then agggeo_string="binary"
elif [[ "$5" -eq 3 ]]; then agggeo_string="monodep"
fi

# suffix for the output directory
SUFFNAME="${model_setup}_${agggeo_string}_xi${xi0}_nz${nz}_lwc${lwc}_ncl${ncl}_nclmass${nclmass}_ssat${ssat}_dtc${dtc}" #"mDADJaggdent_param_xi${xi0}_nz${nz}_lwc${lwc}_ncl${ncl}_ssat${ssat}_dtc${dtc}"
SUFFNAME="${SUFFNAME}_nrp${nrp}_rm${wdm}_rt${rt}_vt${vt}_at${agg}_stick${stick}_dt${dep}_meltt${meltt}_multt${multt}"
SUFFNAME="${SUFFNAME}_h${h1}-${h2}_ba${box_area}"
if [ "$1" == "onlyname" ]; then echo ${0##*/}_${SUFFNAME}; exit ; else echo "not_there"; fi

# scaled variables
nrp=$(echo "${nrp}*1000" | bc -l)
lwc=$(echo "${lwc}*0.0001" | bc -l)
iwc=$(echo "${iwc}*0.00001" | bc -l)
ncl=$(echo "${ncl}*0.0001" | bc -l)
nclmass=$(echo "${nclmass}*0.00000000001" | bc -l)

wdm=$(echo "${wdm}*0.000001" | bc -l)
box_area=$(echo "${box_area}*0.01" | bc -l)
h1=$(echo "${h1}*100." | bc -l)
h2=$(echo "${h2}*100." | bc -l)
ssat=$(echo "${ssat}*0.001" | bc -l)

THIS_DIR=$(pwd -P)
BASE_DIR=${THIS_DIR%/*}
RUN_DIR=${BASE_DIR}/run
#OUT_DIR=${BASE_DIR}//experiments/${0##*/}_${SUFFNAME}
OUT_DIR=/data/optimice/McSnowoutput/BIMOD/experiments/${0##*/}_${SUFFNAME}

echo "Output directory: ${OUT_DIR}"
rm -rf ${OUT_DIR} 
mkdir -p ${OUT_DIR}

# touch a file with Rev. number
if [[ $(git describe 2> /dev/null) ]]; then
  REV=`cd ${BASE_DIR}; git describe`
  touch ${OUT_DIR}/Rev_$REV
else
  echo "WARNING  No Git-Revision file added."
fi


cd ${OUT_DIR}

cp ${BASE_DIR}/build/src/MCSNOW .
cp ${BASE_DIR}/input/* .

# write namelist to file
cat > input.nml <<EOF
test_case_name = ${0##*/}

&general_nml
  msg_level  = 6
  tcase_id   = 103            ! unique test case id
  ini_type   = 2              ! 0: check, 1: box model, 2: 1D model
  bnd_type   = 2              ! 0: zero flux, 1: const xi=xi0, 2: xi ~ flux cdf 4: use 2mom for calculating fluxes
  snowgeo_type = ${geo}       ! 1: bulk, 2: fillin, 3: similarity
  agggeo_type = ${agggeo}     ! 1: M96 mixed agg, 2: MK96 plates + M96 mixed agg, 3: monomer dependent plates
  nucl_type  = 1              ! 0: off, 1: constant, 2: Meyers scheme
  rime_type  = ${rt}          ! 0: no riming, 1: continuous, 2: stochastic
  multiplication_type = ${multt} ! 0: no ice multiplication, 1: rime splintering
  diffusion_type =${dep}      ! 0: no diffusion, 1: vapour diffusion
  mergeNoTresh  = 1000        ! number of super-particles per cell, if threshold is exceeded, similar particle get merged
  mergeRatioLimit = 0.0      ! mass ratio below which two similar drops get merged
  melt_type  = ${meltt}        ! 0: no melting, 1: melting activated
  time_end   = 36000.         ! [s] end time
  dt_1dprof  = 600. !1800.          ! [s] time step for output to file
  dt_2dprof  = 7200.          ! [s] time step for output to file
/
&sp_nml
  iwc         = ${iwc}      ! [kg/m3] ice water content
  iwc_mode2         = 1.60e-05      ! [kg/m3] ice water content
  lwc0        = ${lwc}        ! [kg/m3] liquid water content in the 'LWC zone'
  nrp0        = ${nrp}        ! [1/m3] initial number density of ice particles
  nrp0_mode2        = 0 !2mode is active via nucleation but switched off here!  ! [1/m3] initial number density of ice particles
  xi0         = ${xi0}        ! [1] number of RP per SP
  nu_gam      = 3.545           ! [1] gamma distribution exponent
  mu_gam      = 0.455           ! [1] generalized gamma distribution exponent 
  nu_gam_mode2      = -0.3564           ! [1] gamma distribution exponent
  mu_gam_mode2      =  0.495          ! [1] generalized gamma distribution exponent 
  maxTotalNoSps = 10240000
  dtc         = ${dtc}        ! [s] time step of collision
  !idtmc       = 1             ! [1] (dtm=dtc/idtmc) dtm is time step of sedi.
  idtgm       = 1             ! [1] (dtg=dtm/idtgc) dtg is time step of cond./depo.
  sigma0      = 0.62          ! kernel density estimation factor
  nclrate     = ${ncl}        ! [SP/s] num. new SP in 'nucleation zone' (1d-model)
  nclmass     = ${nclmass} !1e-11         !1.30e-9  !should be 1...e-9 from Joses calculations       ! mean mass of particles after nucleation
  rm          = ${wdm}        ! [m] mean droplet radius in the 1d-model ice particle riming 
  sp_vterm_id = ${vt}         ! 1:Heymsfield, 2:Khvorostyanov
  agg_hist    = -1            ! <0: no history, 0: history with near surface sampling, >0: history with the whole domain sampling
  sp_kernel_id = ${agg}       ! 0: no aggregation. 1: Golovin kernel 2: hydrodynamic kernel
  sp_stick_effi =  ${stick}   ! 0: E_s=1, 1: PK97, 2: Connolly12, 3: 0.5*Connolly12
/
&grid_nml
  dom_top    = ${dom_top}     ! [m]  domain top
  dom_bottom = ${dom_bottom}  ! [m]  domain top
  box_area   = ${box_area}    ! [m2] box area (to form quasi 3d domain)
  nz         = ${nz}          ! [1]  number of vertical grid cells
/
&atmo_nml
  atmo_type  = 1              ! 1: idealized profiles; 2: ECMWF profiles
  ssat       = ${ssat}           ! [1] saturation
  h1         = ${h1}
  h2         = ${h2}
  nh1        = 3000
  nh2        = 3400
/
EOF

# run
time ./MCSNOW

exit 0
